language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "bRk3D21rG1VOR3/83KX7+kqJEZMUkTCAI2yq4wKVVo3ha0SDFyFZjyIeGeTZlEjJVcK4vHvfYrV0Xy1M5TuotuA5qXqb1ETtEQ2LZ9IaX5LIwMS/2sKapJTU5rcEnXGHGMvemTE76denCGnztGGQn3oKR+72iohVwb6/3dFBvBQ="

addons:
  coverity_scan:
    project:
      name: "konradrenner/KoreMenuJPA"
      description: "Your project description here"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command:
    branch_pattern:
